import type { Metadata } from "next";
import { Geist, Geist_Mono, Quintessential } from "next/font/google";
import "./globals.css";

const quintessential = Quintessential({
  variable: "--font-quintessential",
  subsets: ["latin"],
  weight: "400",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quintessential.variable} antialiased min-h-screen overflow-y-auto bg-[url('/websitebackground.jpg')] bg-cover bg-center bg-no-repeat`}>
        {children}
      </body>
    </html>
  );
}
